annotations:
  charts.openshift.io/name: Orchestrator Software Templates Infrastructure for Red Hat Developer Hub
  charts.openshift.io/provider: Red Hat Developer Hub Team
  charts.openshift.io/supportURL: https://issues.redhat.com/browse/RHIDP
apiVersion: v2
name: orchestrator-software-templates-infra
description: >
  A Helm chart to install Openshift GitOps and Openshift Pipelines, which are required operators for installing the Orchestrator Software Templates to be available on RHDH.
kubeVersion: ">= 1.25.0-0"
type: application
sources:
  - https://github.com/redhat-developer/rhdh-software-templates-infrastructure
version: 0.2.0
maintainers:
  - name: Red Hat Developer Hub Team
    url: https://github.com/redhat-developer/rhdh-chart
