annotations:
  charts.openshift.io/name: Orchestrator Infrastructure for Red Hat Developer Hub
  charts.openshift.io/provider: Red Hat Developer Hub Team
  charts.openshift.io/supportURL: https://issues.redhat.com/browse/RHIDP
apiVersion: v2
name: redhat-developer-hub-orchestrator-infra
description: >
  Helm chart to deploy the Orchestrator solution's required infrastructure suite on OpenShift, including
  OpenShift Serverless Operator and OpenShift Serverless Logic Operator, both required to configure Red Hat Developer Hub to use the Orchestrator.
kubeVersion: ">= 1.25.0-0"
maintainers:
  - name: Red Hat Developer Hub Team
    url: https://github.com/redhat-developer/rhdh-chart
type: application
sources:
  - https://github.com/redhat-developer/rhdh-chart
version: 0.1.0
