annotations:
  artifacthub.io/category: integration-delivery
  artifacthub.io/license: Apache-2.0
  artifacthub.io/links: |
    - name: support
      url: https://github.com/redhat-developer/rhdh-chart/issues
    - name: Chart Source
      url: https://github.com/redhat-developer/rhdh-chart
    - name: Default Image Source
      url: https://github.com/janus-idp/backstage-showcase
  charts.openshift.io/name: Backstage
  charts.openshift.io/provider: Red Hat Developer Hub Team
  charts.openshift.io/supportURL: https://github.com/redhat-developer/rhdh-chart/issues
apiVersion: v2
description: A Helm chart for deploying RHDH (a Backstage application)
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: "2.14.1"
  - name: backstage
    repository: https://backstage.github.io/charts
    version: "1.9.1"
    alias: upstream
home: https://redhat-developer.github.io/rhdh-chart/
icon: https://avatars.githubusercontent.com/u/117844786
keywords:
  - backstage
  - idp
  - janus-idp
kubeVersion: ">= 1.25.0-0"
maintainers:
  - name: Red Hat Developer Hub Team
    url: https://github.com/redhat-developer/rhdh-chart
name: backstage
type: application
sources:
  - https://github.com/redhat-developer/rhdh-chart
  - https://github.com/janus-idp/backstage-showcase
# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 2.15.1
